---
- name: grafana config directory is present
  ansible.builtin.file:
    path: "{{ grafana_conf_dir }}"
    owner: "root"
    group: "root"
    mode: "755"
    state: "directory"
- name: test
  ansible.builtin.template:
    dest: "{{ grafana_conf_dir }}/grafana.ini"
