---
- name: configure.yml | config is generated
  ansible.builtin.template:
    src: "templates/grafana.ini.j2"
    dest: "{{ grafana_conf_dir }}/grafana.ini"
    owner: "root"
    group: "{{ grafana_group }}"
    mode: "0640"
