---
- name: grafana default parameters file is generated
  ansible.builtin.template:
    src: "templates/grafana-server.j2"
    dest: "/etc/default/grafana-server"
- name: grafana unit file is generated
  ansible.builtin.template:
    src: "templates/grafana.service.j2"
    dest: "{{ grafana_unit_dir }}/grafana-server.service"
  notify:
    - systemd daemon-reload
- name: grafana PID file dir is present
  ansible.builtin.file:
    path: "/run/grafana"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "750"
    state: "directory"
